### ISSUE TITLE
t/300-perlenv.t fails with bleadperl (5.39.x)

### ISSUE THREAD

**Issue by eserte** [mkende/ptp#1]
The test suite fails with the latest development perls:
```
#   Failed test 'tie allowed with --safe 1'
#   at t/300-perlenv.t line 62.
# Looks like you failed 1 test of 37.
t/300-perlenv.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/37 subtests 
```

If you think that this is a perl regression, or the change here is not mentioned in perldelta, then probably an issue at the perl tracker ("BBC", blead breaks cpan) should be created.

**Comment by mkende** [comment]
At this stage I believe that this is an issue with Perl itself as documented in https://github.com/Perl/perl5/issues/21867. Thanks for letting me know about this.
